spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql1
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-secret-key-my-secret-key-my-secret-key
  expiration: 3600000

